name: mix test

on:
  push:
    paths-ignore:
      - README.md
      - .gitignore
    branches:
      - main
      - dev/*
  pull_request:
    branches:
      - master

jobs:
  # Refactoring duplicated yaml is currently not possible
  # because Github does not support anchor syntax (& and *) now.
  elixir_1_14:
    runs-on: ubuntu-20.04
    name: Test on Elixir ${{matrix.elixir}} / OTP ${{matrix.otp}}
    strategy:
      matrix:
        elixir: [1.14.x]
        otp: [23.x, 24.x, 25.x]
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{matrix.elixir}}
          otp-version: ${{matrix.otp}}
      - run: mix deps.get
      - run: mix test
  elixir_1_13:
    runs-on: ubuntu-20.04
    name: Test on Elixir ${{matrix.elixir}} / OTP ${{matrix.otp}}
    strategy:
      matrix:
        elixir: [1.13.x]
        otp: [22.x, 23.x, 24.x]
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{matrix.elixir}}
          otp-version: ${{matrix.otp}}
      - run: mix deps.get
      - run: mix test
  elixir_1_12:
    runs-on: ubuntu-20.04
    name: Test on Elixir ${{matrix.elixir}} / OTP ${{matrix.otp}}
    strategy:
      matrix:
        elixir: [1.12.x]
        otp: [22.x, 23.x, 24.x]
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{matrix.elixir}}
          otp-version: ${{matrix.otp}}
      - run: mix deps.get
      - run: mix test
